Numpy 

In [1]:
!pip install numpy

In [2]:
#importing the module
import numpy as np #here np is the alias name

In [3]:
my_list=[1,2,3,4,5]

In [4]:
type(my_list)

list

In [5]:
my_array=np.array(my_list) #np.array() will convert the list to an array

In [6]:
print(my_array)

[1 2 3 4 5]


In [7]:
type(my_array) #here nd means n dimentional, in this case the value of n=1

numpy.ndarray

In [8]:
#multinested array
my_list_1=[1,2,3,4,5]
my_list_2=[3,4,5,3,2]
my_list_3=[5,9,8,0,1]

arr=np.array([my_list_1,my_list_2,my_list_3])

In [9]:
print(arr)

[[1 2 3 4 5]
 [3 4 5 3 2]
 [5 9 8 0 1]]


In [10]:
arr.shape #.shape talks about the number of rows and then the number of columns 

(3, 5)

In [12]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 3],
       [4, 5, 3],
       [2, 5, 9],
       [8, 0, 1]])

In [13]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 3, 4, 5, 3, 2, 5, 9, 8, 0, 1]])

In [11]:
arr.reshape(4,5) 

ValueError: cannot reshape array of size 15 into shape (4,5)

In [14]:
arr_new=np.array([[1,2,3,4],[2,4,5,6],[4,9,0,0]])

In [15]:
print(arr_new)

[[1 2 3 4]
 [2 4 5 6]
 [4 9 0 0]]


In [17]:
arr_new.shape

(3, 4)

In [19]:
arr_new.reshape(2,6)

array([[1, 2, 3, 4, 2, 4],
       [5, 6, 4, 9, 0, 0]])

In [20]:
new_arr=arr_new.reshape(2,2,3) #first - number of matrics, second and third - size of each matrix

In [21]:
print(new_arr)

[[[1 2 3]
  [4 2 4]]

 [[5 6 4]
  [9 0 0]]]


In [22]:
new_arr_one=arr_new.reshape(3,2,2)

In [23]:
print(new_arr_one)

[[[1 2]
  [3 4]]

 [[2 4]
  [5 6]]

 [[4 9]
  [0 0]]]


In [24]:
#Basic operations with matrics

In [25]:
a=np.array([1,2,3,4,5])

In [26]:
print("adding 1 to each element",a+1)

adding 1 to each element [2 3 4 5 6]


In [27]:
print("substracting 2 from each element",a-2)

substracting 2 from each element [-1  0  1  2  3]


In [28]:
print("multiply each element by 5",a*5)

multiply each element by 5 [ 5 10 15 20 25]


In [29]:
print("dividing each element by 2",a/2)

dividing each element by 2 [0.5 1.  1.5 2.  2.5]


In [30]:
print("square of each element",a**2)

square of each element [ 1  4  9 16 25]


In [31]:
b=np.array([[3,4,5],[8,9,1],[1,1,2]])

In [32]:
print(b)

[[3 4 5]
 [8 9 1]
 [1 1 2]]


In [33]:
print("largest element from this matrix is",b.max())

largest element from this matrix is 9


In [34]:
print("smallest element from this matrix is", b.min())

smallest element from this matrix is 1


In [35]:
print("sum of all the elements from this matrix",b.sum())

sum of all the elements from this matrix 34


In [36]:
print("transpose of the matrix",b.T) #.T will convert the rows into columns and columns into rows

transpose of the matrix [[3 8 1]
 [4 9 1]
 [5 1 2]]


In [38]:
print("eigen values and eigen vectors of the given matrix",np.linalg.eig(b))

eigen values and eigen vectors of the given matrix EigResult(eigenvalues=array([12.90893219, -0.63010533,  1.72117314]), eigenvectors=array([[-0.42351784, -0.77080884,  0.58526014],
       [-0.89775441,  0.63496947, -0.69956984],
       [-0.12111838,  0.05164788,  0.40996659]]))


In [39]:
mat_1=np.array([[1,2],[3,4]])
mat_2=np.array([[5,6],[7,8]])

In [40]:
print("adding the two matrics together",mat_1+mat_2)

adding the two matrics together [[ 6  8]
 [10 12]]


In [41]:
print("multipllying the two matrics together",mat_1*mat_2)

multipllying the two matrics together [[ 5 12]
 [21 32]]


In [42]:
#generate numbers(sequential as well as random)

In [43]:
p=np.arange(1,10) #arange() helps in generating sequential data in a given range 

In [44]:
print(p)

[1 2 3 4 5 6 7 8 9]


In [45]:
np.arange(1,10,2) #here 2 represents the step size 

array([1, 3, 5, 7, 9])

In [46]:
np.arange(1,15,3)

array([ 1,  4,  7, 10, 13])

In [47]:
np.linspace(1,10,50) #here 10 will not exclusive in nature and 50 here represents the number of outputs to be generated

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [48]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [51]:
np.random.rand(3,4) #here 3 is the number of rows and 4 is the number of columns
#here in random.rand the range is 0-1 bydefault (where 1 is exclusive)

array([[0.61439004, 0.35588244, 0.33563287, 0.39105675],
       [0.92852672, 0.27717218, 0.94850726, 0.25998921],
       [0.16441   , 0.85558367, 0.09954204, 0.6419346 ]])

In [53]:
np.random.rand(4,5)

array([[0.29448821, 0.10124601, 0.15010508, 0.44599566, 0.9407843 ],
       [0.00235638, 0.68738103, 0.33374224, 0.81346295, 0.73807054],
       [0.58843738, 0.21939912, 0.25488889, 0.02511606, 0.79620151],
       [0.60263372, 0.9198507 , 0.16590717, 0.5169889 , 0.6846393 ]])

In [57]:
np.random.rand() 

0.5757315688633571

In [64]:
np.random.randint(1,10) #here 1 to 10 represents the range (10 being exclusive)
#here we get whole numbers as output

3

In [68]:
np.random.randint(1,20,4) #here 4 represents the number of output 

array([11, 12, 18, 13])